sudo: false

notifications:
  email: false

branches:
  only:
    - master

os: osx
osx_image: xcode12

env:
  - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"
  - DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone 7"
  - DESTINATION="platform=iOS Simulator,OS=12.4,name=iPhone 7"
  - DESTINATION="platform=iOS Simulator,OS=13.5,name=iPhone 8"
  - DESTINATION="platform=iOS Simulator,OS=14.0,name=iPhone 8"

script:
  xcodebuild -scheme "BlueprintUI-Package" test -destination "$DESTINATION"

jobs:
  include:
  - name: "Cocoapods BlueprintUI"
    script: xcodebuild -workspace "SampleApp.xcworkspace" -scheme "BlueprintUI-Unit-Tests" -destination "platform=iOS Simulator,OS=14.0,name=iPhone 8"
    before_install:
      - cd SampleApp
      - bundle install
      - bundle exec pod repo update
      - bundle exec pod install
